INSERT INTO users (
    email,
    password,
    name,
    role,
    credit_rating,
    provider,
    provider_id,
    created_at,
    deleted_at,
    updated_at,
    notification,
    user_key
)
VALUES
    (
        'test1@test.com',
        '1234',
        '박성현',
        'PREENTREPRENEUR',
        NULL,
        'LOCAL',
        NULL,
        CURRENT_TIMESTAMP,
        NULL,
        NULL,
        TRUE,
        '1111'
    ),
    (
        'test2@test.com',
        '1234',
        '황문규',
        'PREENTREPRENEUR',
        NULL,
        'LOCAL',
        NULL,
        CURRENT_TIMESTAMP,
        NULL,
        NULL,
        TRUE,
        '1111'
    ),
    (
        'test3@test.com',
        '1234',
        '권병수',
        'PREENTREPRENEUR',
        NULL,
        'LOCAL',
        NULL,
        CURRENT_TIMESTAMP,
        NULL,
        NULL,
        TRUE,
        '1111'
    );