from enum import StrEnum


class SourceType(StrEnum):
    USER = "USER"
    BUSINESS = "BUSINESS"
    MYDATA = "MYDATA"
    ACCOUNT = "ACCOUNT"
    PROGRAM = "PROGRAM"
    RAG = "RAG"


class FieldType(StrEnum):
    DIRECT = "DIRECT"
    COMPUTED = "COMPUTED"
    GENERATED = "GENERATED"
    USER_INPUT = "USER_INPUT"


class SourceKey(StrEnum):
    USER_NAME = "USER_NAME"
    USER_EMAIL = "USER_EMAIL"
    USER_BIRTH_DATE = "USER_BIRTH_DATE"
    CREDIT_RATING = "CREDIT_RATING"
    BUSINESS_BRN = "BUSINESS_BRN"
    BUSINESS_NAME = "BUSINESS_NAME"
    BUSINESS_ADDRESS = "BUSINESS_ADDRESS"
    BUSINESS_REGION = "BUSINESS_REGION"
    BUSINESS_CATEGORY = "BUSINESS_CATEGORY"
    EMPLOYEE_COUNT = "EMPLOYEE_COUNT"
    OPEN_DATE = "OPEN_DATE"
    BUSINESS_AGE_MONTHS = "BUSINESS_AGE_MONTHS"
    REVENUE_SUM = "REVENUE_SUM"
    REVENUE_AVERAGE = "REVENUE_AVERAGE"
    TAX_SUM = "TAX_SUM"
    TAX_AVERAGE = "TAX_AVERAGE"
    INSURANCE_LIST = "INSURANCE_LIST"
    INSURANCE_ENROLLED = "INSURANCE_ENROLLED"
    PROGRAM_DRAFT_DATE = "PROGRAM_DRAFT_DATE"
    PROGRAM_NAME = "PROGRAM_NAME"
    PROGRAM_ORGANIZATION = "PROGRAM_ORGANIZATION"
    PROGRAM_EXECUTION_ORGANIZATION = "PROGRAM_EXECUTION_ORGANIZATION"
    PROGRAM_TYPE = "PROGRAM_TYPE"
    PROGRAM_START_DATE = "PROGRAM_START_DATE"
    PROGRAM_END_DATE = "PROGRAM_END_DATE"
    PROGRAM_SUMMARY = "PROGRAM_SUMMARY"
    PROGRAM_APPLICATION_METHOD = "PROGRAM_APPLICATION_METHOD"
    PROGRAM_REFERENCE = "PROGRAM_REFERENCE"
    PROGRAM_MIN_BALANCE = "PROGRAM_MIN_BALANCE"
    PROGRAM_MAX_BALANCE = "PROGRAM_MAX_BALANCE"
    PROGRAM_INTEREST_RATE = "PROGRAM_INTEREST_RATE"
    PROGRAM_RAG = "PROGRAM_RAG"

