-- ============================================================
-- Document Agent Schema
-- ============================================================


-- ============================================================
-- 1. 문서 템플릿
-- program_document / loan_document의 작성용 서류를
-- Agent가 사용할 수 있는 표준 템플릿으로 관리
-- ============================================================

CREATE TABLE document_template (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   program_document_id BIGINT
                                       REFERENCES program_document(id) ON DELETE CASCADE,

                                   loan_document_id BIGINT
                                       REFERENCES loan_document(id) ON DELETE CASCADE,

    -- 사용자가 받은 원본 파일 형식
                                   original_format VARCHAR(10) NOT NULL,

    -- 내부 처리용 표준 파일 형식
    -- HWP -> HWPX
    -- DOC -> DOCX
                                   normalized_format VARCHAR(10),

    -- 변환된 실제 파일 위치
                                   normalized_path VARCHAR(500),

    -- 문서 파싱 상태
                                   parse_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    -- 파싱 실패 시 원인
                                   parse_error TEXT,

    -- 스키마 버전
                                   schema_version INT NOT NULL DEFAULT 1,

                                   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- 지원사업 문서 / 대출 문서 중 정확히 하나만 지정
                                   CONSTRAINT chk_document_template_target
                                       CHECK (
                                           (program_document_id IS NULL)
                                               <> (loan_document_id IS NULL)
                                           ),

                                   CONSTRAINT chk_document_template_original_format
                                       CHECK (
                                           original_format IN (
                                                               'HWP',
                                                               'HWPX',
                                                               'DOC',
                                                               'DOCX'
                                               )
                                           ),

                                   CONSTRAINT chk_document_template_normalized_format
                                       CHECK (
                                           normalized_format IS NULL
                                               OR normalized_format IN (
                                                                        'HWPX',
                                                                        'DOCX'
                                               )
                                           ),

                                   CONSTRAINT chk_document_template_parse_status
                                       CHECK (
                                           parse_status IN (
                                                            'PENDING',
                                                            'PARSING',
                                                            'COMPLETED',
                                                            'FAILED'
                                               )
                                           ),

                                   CONSTRAINT chk_document_template_schema_version
                                       CHECK (schema_version >= 1)
);


COMMENT ON TABLE document_template
    IS '문서 작성 Agent가 사용하는 문서 템플릿';

COMMENT ON COLUMN document_template.original_format
    IS '원본 파일 형식: HWP/HWPX/DOC/DOCX';

COMMENT ON COLUMN document_template.normalized_format
    IS 'Agent 내부 처리용 표준 형식: HWPX/DOCX';

COMMENT ON COLUMN document_template.normalized_path
    IS '변환 완료된 표준 문서의 저장 경로';

COMMENT ON COLUMN document_template.parse_status
    IS 'PENDING/PARSING/COMPLETED/FAILED';


CREATE UNIQUE INDEX uq_document_template_program_version
    ON document_template(program_document_id, schema_version)
    WHERE program_document_id IS NOT NULL;

CREATE UNIQUE INDEX uq_document_template_loan_version
    ON document_template(loan_document_id, schema_version)
    WHERE loan_document_id IS NOT NULL;



-- ============================================================
-- 2. 문서 필드 스키마
-- 문서의 실제 작성 칸에 대한 정의
-- ============================================================

CREATE TABLE document_field_schema (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                       template_id BIGINT NOT NULL
                                           REFERENCES document_template(id) ON DELETE CASCADE,

    -- Agent 내부에서 사용하는 고유 키
    -- ex) owner_name, business_purpose
                                       field_key VARCHAR(100) NOT NULL,

    -- 실제 문서에 표시되는 이름
    -- ex) 대표자 성명, 사업 추진 목적
                                       field_label VARCHAR(255) NOT NULL,

    -- 문서 내 순서
                                       field_order INT NOT NULL,

    -- 작성 방식
                                       field_type VARCHAR(20) NOT NULL,

    -- 최종 값의 데이터 타입
                                       value_type VARCHAR(20) NOT NULL DEFAULT 'TEXT',

                                       required BOOLEAN NOT NULL DEFAULT FALSE,

    -- LLM 작성 시 사용할 필드별 작성 지침
                                       instruction TEXT,

                                       min_length INT,
                                       max_length INT,

    -- 실제 문서에서 값을 작성해야 할 위치
    -- DOCX/HWPX별 위치 정보를 JSON으로 저장
                                       location_info JSONB NOT NULL,

    -- 기타 필드 제약조건
                                       constraints JSONB,

                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT uq_document_field
                                           UNIQUE(template_id, field_key),

                                       CONSTRAINT uq_document_field_order
                                           UNIQUE(template_id, field_order),

                                       CONSTRAINT chk_document_field_type
                                           CHECK (
                                               field_type IN (
                                                              'DIRECT',
                                                              'COMPUTED',
                                                              'GENERATED',
                                                              'USER_INPUT'
                                                   )
                                               ),

                                       CONSTRAINT chk_document_field_value_type
                                           CHECK (
                                               value_type IN (
                                                              'TEXT',
                                                              'NUMBER',
                                                              'DATE',
                                                              'BOOLEAN',
                                                              'JSON'
                                                   )
                                               ),

                                       CONSTRAINT chk_document_field_order_positive
                                           CHECK (field_order >= 0),

                                       CONSTRAINT chk_document_field_min_length
                                           CHECK (
                                               min_length IS NULL
                                                   OR min_length >= 0
                                               ),

                                       CONSTRAINT chk_document_field_max_length
                                           CHECK (
                                               max_length IS NULL
                                                   OR max_length >= 0
                                               ),

                                       CONSTRAINT chk_document_field_length
                                           CHECK (
                                               min_length IS NULL
                                                   OR max_length IS NULL
                                                   OR min_length <= max_length
                                               )
);


COMMENT ON TABLE document_field_schema
    IS '문서 작성 Agent가 사용하는 필드 정의';

COMMENT ON COLUMN document_field_schema.field_type
    IS 'DIRECT/COMPUTED/GENERATED/USER_INPUT';

COMMENT ON COLUMN document_field_schema.instruction
    IS 'GENERATED 필드 작성 시 LLM에 전달할 작성 지침';

COMMENT ON COLUMN document_field_schema.location_info
    IS 'HWPX/DOCX 내부에서 실제 값을 작성할 위치 정보';



CREATE INDEX idx_document_field_schema_template
    ON document_field_schema(template_id);



-- ============================================================
-- 3. 문서 필드 데이터 출처
-- 각 필드를 작성하기 위해 어떤 데이터가 필요한지 정의
-- 하나의 GENERATED 필드는 여러 개의 source를 가질 수 있음
-- ============================================================

CREATE TABLE document_field_source (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                       field_schema_id BIGINT NOT NULL
                                           REFERENCES document_field_schema(id) ON DELETE CASCADE,

    -- 데이터 영역
                                       source_type VARCHAR(30) NOT NULL,

    -- FastAPI SourceRegistry에서 해석할 논리적인 Key
    -- ex)
    -- USER_NAME
    -- BUSINESS_NAME
    -- REVENUE_SUM
    -- PROGRAM_RAG
                                       source_key VARCHAR(100),

                                       required BOOLEAN NOT NULL DEFAULT TRUE,

    -- 여러 데이터가 필요한 경우 우선순위
                                       priority INT NOT NULL DEFAULT 1,

    -- RAG 검색 시 사용할 검색 방향/힌트
                                       query_hint TEXT,

    -- 계산 및 조회 시 필요한 추가 파라미터
    --
    -- ex)
    -- {
    --   "months": 12
    -- }
                                       source_params JSONB,

                                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                       CONSTRAINT chk_document_field_source_type
                                           CHECK (
                                               source_type IN (
                                                               'USER',
                                                               'BUSINESS',
                                                               'MYDATA',
                                                               'ACCOUNT',
                                                               'PROGRAM',
                                                               'LOAN',
                                                               'RAG'
                                                   )
                                               ),

                                       CONSTRAINT chk_document_field_source_priority
                                           CHECK (priority >= 1),

    -- 일반 데이터 Source는 source_key가 필수.
    -- RAG는 query_hint 중심으로 검색할 수도 있으므로 NULL 허용.
                                       CONSTRAINT chk_document_field_source_key
                                           CHECK (
                                               source_type = 'RAG'
                                                   OR source_key IS NOT NULL
                                               )
);


COMMENT ON TABLE document_field_source
    IS '문서 필드를 작성하기 위해 필요한 데이터 출처';

COMMENT ON COLUMN document_field_source.source_type
    IS 'USER/BUSINESS/MYDATA/ACCOUNT/PROGRAM/LOAN/RAG';

COMMENT ON COLUMN document_field_source.source_key
    IS 'FastAPI SourceRegistry에서 사용하는 논리적인 데이터 Key';

COMMENT ON COLUMN document_field_source.query_hint
    IS 'RAG 검색 query 생성을 위한 검색 방향';

COMMENT ON COLUMN document_field_source.source_params
    IS '기간 등 Source 조회/계산에 필요한 추가 파라미터';


CREATE INDEX idx_document_field_source_field
    ON document_field_source(field_schema_id);

CREATE INDEX idx_document_field_source_key
    ON document_field_source(source_key);