-- =====================================================================
-- schema.sql  (PostgreSQL 15+ / pgvector 0.5+)
--
-- ERD 대비 변경 사항
--   * user -> users (PG 예약어 회피)
--   * 모든 단일 id PK: BIGINT GENERATED BY DEFAULT AS IDENTITY
--     (외부 데이터 적재 시 id 명시 INSERT 가능)
--   * verify.id VARCHAR(255) -> BIGINT
--   * business_info.business_code_id INT -> BIGINT (minor_code.id 와 타입 일치)
--   * code_insurance.insuranc_id -> insurance_id (오타)
--   * suggest_loan FK 방향 수정
--   * ERD 관계선 기준 FK 전부 추가
--   * deleted_at DEFAULT 제거 (삭제 전에는 NULL 이어야 함)
--   * program_chunk: RAG 용 설계 (KoE5 / KURE-v1, 1024차원)
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------
-- 0. 초기화 (필요 시 주석 해제)
-- ---------------------------------------------------------------------
-- DROP TABLE IF EXISTS
--   program_chunk, program_document, program_condition, suggest_support_program,
--   application_document, application, suggest_loan, loan_document, bookmark,
--   business_tax, insurance_checklist, code_insurance, mydata_insurance, mydata_tax,
--   mydata, notification, account, business_info, verify, seoul_commercial_data,
--   region, minor_code, sub_code, major_code, insurance, loan, support_program, users
-- CASCADE;

-- =====================================================================
-- 1. 참조/코드 테이블
-- =====================================================================

CREATE TABLE major_code (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code    VARCHAR(8)   NOT NULL UNIQUE,
    name    VARCHAR(100) NOT NULL
);
COMMENT ON TABLE major_code IS '업종 분류 코드 (대분류)';

CREATE TABLE sub_code (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    major_id  BIGINT       NOT NULL REFERENCES major_code(id),
    code      VARCHAR(8)   NOT NULL UNIQUE,
    name      VARCHAR(100) NOT NULL
);
COMMENT ON TABLE sub_code IS '업종 분류 코드 (중분류)';

CREATE TABLE minor_code (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_id  BIGINT       NOT NULL REFERENCES sub_code(id),
    code    VARCHAR(8)   NOT NULL UNIQUE,
    name    VARCHAR(100) NOT NULL
);
COMMENT ON TABLE minor_code IS '업종 분류 코드 (소분류)';

CREATE TABLE region (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code  VARCHAR(20) NOT NULL UNIQUE,
    region_name  VARCHAR(20) NOT NULL
);
COMMENT ON TABLE region IS '행정동';

CREATE TABLE seoul_commercial_data (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id          BIGINT      NOT NULL REFERENCES region(id),
    business_code      VARCHAR(20) NOT NULL,
    business_name      VARCHAR(20) NOT NULL,
    month_revenue      BIGINT      NOT NULL,
    week_revenue       BIGINT      NOT NULL,
    weekend_revenue    BIGINT      NOT NULL,
    male_revenue       BIGINT      NOT NULL,
    female_revenue     BIGINT      NOT NULL,
    total_count        BIGINT      NOT NULL,
    open_count         BIGINT      NOT NULL,
    close_count        BIGINT      NOT NULL,
    total_population   BIGINT      NOT NULL,
    male_population    BIGINT      NOT NULL,
    female_population  BIGINT      NOT NULL
);
COMMENT ON TABLE seoul_commercial_data IS '서울시 상권 정보';

CREATE TABLE insurance (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(30)  NOT NULL,
    info       VARCHAR(255) NOT NULL,
    condition  TEXT         NOT NULL
);
COMMENT ON TABLE insurance IS '의무 보험';
COMMENT ON COLUMN insurance.name IS '의무보험 이름';

CREATE TABLE code_insurance (
    code_id       BIGINT NOT NULL REFERENCES minor_code(id) ON DELETE CASCADE,
    insurance_id  BIGINT NOT NULL REFERENCES insurance(id)  ON DELETE CASCADE,
    PRIMARY KEY (code_id, insurance_id)
);
COMMENT ON TABLE code_insurance IS '업종 코드 - 의무 보험 매핑';

-- =====================================================================
-- 2. 회원
-- =====================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password      VARCHAR(255),
    name          VARCHAR(100) NOT NULL,
    role          VARCHAR(20),
    phone_number  VARCHAR(20),
    credit_rating VARCHAR(3),
    provider      VARCHAR(10)  NOT NULL,
    provider_id   VARCHAR(255),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    notification  BOOLEAN      NOT NULL DEFAULT TRUE,
    user_key      VARCHAR(60)  NOT NULL,
    CONSTRAINT chk_users_role     CHECK (role IN ('ENTREPRENEUR', 'PREENTREPRENEUR')),
    CONSTRAINT chk_users_provider CHECK (provider IN ('LOCAL', 'GOOGLE'))
);
COMMENT ON TABLE  users IS '회원 (ERD: user)';
COMMENT ON COLUMN users.role         IS '창업자 / 예비 창업자 (ENTREPRENEUR / PREENTREPRENEUR)';
COMMENT ON COLUMN users.provider     IS 'LOCAL / GOOGLE';
COMMENT ON COLUMN users.created_at   IS '가입날짜';
COMMENT ON COLUMN users.deleted_at   IS '탈퇴날짜';
COMMENT ON COLUMN users.updated_at   IS '수정날짜';
COMMENT ON COLUMN users.notification IS '알람 동의 여부';
COMMENT ON COLUMN users.user_key     IS '싸피 금융망 user key';

CREATE TABLE account (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    bank_name         VARCHAR(20) NOT NULL,
    account_no        VARCHAR(16) NOT NULL,
    type              VARCHAR(10) NOT NULL,
    transfer_account  VARCHAR(16),
    CONSTRAINT uq_account_no UNIQUE (account_no)
);
COMMENT ON TABLE  account IS '사용자 계좌';
COMMENT ON COLUMN account.type IS '입출금 | 대출';
CREATE INDEX idx_account_user ON account(user_id);

CREATE TABLE notification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type        VARCHAR(20) NOT NULL,
    is_checked  BOOLEAN     NOT NULL DEFAULT FALSE,
    target_id   BIGINT      NOT NULL,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP
);
COMMENT ON TABLE  notification IS '알림';
COMMENT ON COLUMN notification.type       IS '신규 지원사업 / 신규 대출상품 / 지원사업 심사 완료 / 대출 심사 완료';
COMMENT ON COLUMN notification.is_checked IS '조회 여부';
COMMENT ON COLUMN notification.target_id  IS '알람을 발생시킨 도메인의 id';
COMMENT ON COLUMN notification.deleted_at IS '알람 삭제 시각';
CREATE INDEX idx_notification_user ON notification(user_id, is_checked);

-- =====================================================================
-- 3. 업체
-- =====================================================================

CREATE TABLE business_info (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    business_code_id  BIGINT       NOT NULL REFERENCES minor_code(id),
    brn               VARCHAR(255) NOT NULL UNIQUE,
    business_name     VARCHAR(100) NOT NULL,
    address           VARCHAR(255) NOT NULL,
    region            VARCHAR(100) NOT NULL,
    employee_count    INT          NOT NULL,
    open_date         DATE         NOT NULL
);
COMMENT ON TABLE  business_info IS '업체 정보';
COMMENT ON COLUMN business_info.brn IS '사업자등록번호';
CREATE INDEX idx_business_info_user ON business_info(user_id);

CREATE TABLE business_tax (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id  BIGINT NOT NULL REFERENCES business_info(id) ON DELETE CASCADE,
    period       DATE   NOT NULL,
    revenue      BIGINT NOT NULL DEFAULT 0,
    tax          BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_business_tax_period UNIQUE (business_id, period)
);
COMMENT ON TABLE  business_tax IS '업체 매출 세액';
COMMENT ON COLUMN business_tax.period IS '귀속 월. 해당 월 1일로 저장 (예: 2026-08-01)';

CREATE TABLE insurance_checklist (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT      NOT NULL REFERENCES business_info(id) ON DELETE CASCADE,
    insurance_id  BIGINT      NOT NULL REFERENCES insurance(id),
    status        VARCHAR(20) NOT NULL,
    CONSTRAINT uq_insurance_checklist UNIQUE (business_id, insurance_id),
    CONSTRAINT chk_insurance_checklist_status
        CHECK (status IN ('COMPLETED', 'NEEDS_VERIFICATION', 'REQUIRED', 'EXEMPT'))
);
COMMENT ON TABLE  insurance_checklist IS '보험 가입 여부';
COMMENT ON COLUMN insurance_checklist.status IS '가입 완료 / 확인 필요 / 가입 필요 / 가입 제외';

CREATE TABLE verify (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brn               VARCHAR(30)  NOT NULL UNIQUE,
    name              VARCHAR(30)  NOT NULL,
    type              VARCHAR(30)  NOT NULL,
    business_name     VARCHAR(100) NOT NULL,
    business_code_id  BIGINT       NOT NULL REFERENCES minor_code(id),
    address           VARCHAR(255) NOT NULL,
    open_date         DATE         NOT NULL,
    is_close          BOOLEAN      NOT NULL,
    employee_count    INT          NOT NULL,
    region            VARCHAR(100) NOT NULL
);
COMMENT ON TABLE verify IS '국세청 사업자 정보 (검증용 mock)';

-- =====================================================================
-- 4. 마이데이터 (mock)
-- =====================================================================

CREATE TABLE mydata (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brn  VARCHAR(30) NOT NULL UNIQUE
);
COMMENT ON TABLE mydata IS '마이데이터';

CREATE TABLE mydata_tax (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mydata_id  BIGINT NOT NULL REFERENCES mydata(id) ON DELETE CASCADE,
    period     DATE   NOT NULL,
    revenue    BIGINT NOT NULL,
    tax        BIGINT NOT NULL
);
COMMENT ON TABLE mydata_tax IS '업체 매출 세액 정보 (마이데이터)';

CREATE TABLE mydata_insurance (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mydata_id     BIGINT NOT NULL REFERENCES mydata(id) ON DELETE CASCADE,
    insurance_id  BIGINT NOT NULL REFERENCES insurance(id)
);
COMMENT ON TABLE mydata_insurance IS '가입 보험 (마이데이터)';

-- =====================================================================
-- 5. 대출 상품
-- =====================================================================

CREATE TABLE loan (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name            VARCHAR(30)      NOT NULL,
    account_type_unique_no  VARCHAR(20),
    bank_name               VARCHAR(255)     NOT NULL,
    description             VARCHAR(255),
    interest_rate           DOUBLE PRECISION NOT NULL,
    min_loan_balance        BIGINT           NOT NULL,
    max_loan_balance        BIGINT           NOT NULL,
    period                  INT              NOT NULL,
    rating_name             VARCHAR(3)       NOT NULL,
    is_start                BOOLEAN          NOT NULL,
    employee_num            BOOLEAN          NOT NULL,
    firm_age                INT              NOT NULL
);
COMMENT ON TABLE  loan IS '대출 상품';
COMMENT ON COLUMN loan.account_type_unique_no IS '금융 도메인에 등록된 고유 번호';
COMMENT ON COLUMN loan.rating_name  IS '최소 가입 가능 신용등급명';
COMMENT ON COLUMN loan.is_start     IS '실제 창업 시작 여부';
COMMENT ON COLUMN loan.employee_num IS '근로자 관련 조건 유무';
COMMENT ON COLUMN loan.firm_age     IS '가입 가능 최소 업력';

CREATE TABLE loan_document (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id   BIGINT       NOT NULL REFERENCES loan(id) ON DELETE CASCADE,
    doc_name  VARCHAR(100) NOT NULL,
    type      VARCHAR(10)  NOT NULL,
    url       VARCHAR(500)
);
COMMENT ON TABLE  loan_document IS '대출 관련 서류';
COMMENT ON COLUMN loan_document.type IS '제출용 | 작성용';

CREATE TABLE suggest_loan (
    business_id  BIGINT    NOT NULL REFERENCES business_info(id) ON DELETE CASCADE,
    loan_id      BIGINT    NOT NULL REFERENCES loan(id)          ON DELETE CASCADE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (business_id, loan_id)
);
COMMENT ON TABLE suggest_loan IS '업체별 대출 상품 추천';

-- =====================================================================
-- 6. 지원 사업
-- =====================================================================

CREATE TABLE support_program (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pblanc_nm            VARCHAR(100)  NOT NULL,
    jrsdinstt_nm         VARCHAR(50)   NOT NULL,
    excinstt_nm          VARCHAR(50)   NOT NULL,
    type                 VARCHAR(10)   NOT NULL,
    start_date           DATE,
    end_date             DATE,
    bsns_sumry_cn        VARCHAR(1000),
    reqst_mth_papers_cn  VARCHAR(255),
    refrnc_nm            VARCHAR(100),
    rcept_engn_hmpg_url  VARCHAR(1000),
    print_flpth_nm       VARCHAR(1000),
    min_balance          BIGINT,
    max_balance          BIGINT,
    interest_rate        DOUBLE PRECISION
);
COMMENT ON TABLE  support_program IS '지원 사업';
COMMENT ON COLUMN support_program.type       IS '지원금 / 대출 / 기타';
COMMENT ON COLUMN support_program.start_date IS 'start/end 모두 NULL 이면 예산 소진 시 마감';
CREATE INDEX idx_support_program_period ON support_program(start_date, end_date);

CREATE TABLE program_condition (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_program_id  BIGINT NOT NULL REFERENCES support_program(id) ON DELETE CASCADE
);
COMMENT ON TABLE program_condition IS '지원 사업 조건 (컬럼 추가 예정)';

CREATE TABLE program_document (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_program_id  BIGINT      NOT NULL REFERENCES support_program(id) ON DELETE CASCADE,
    type                VARCHAR(10) NOT NULL,
    url                 VARCHAR(500)
);
COMMENT ON TABLE  program_document IS '지원 사업 관련 서류';
COMMENT ON COLUMN program_document.type IS '제출용 | 작성용';

CREATE TABLE program_chunk (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_program_id  BIGINT       NOT NULL REFERENCES support_program(id) ON DELETE CASCADE,
    chunk_index         INT          NOT NULL,
    content             TEXT         NOT NULL,
    embedding           VECTOR(1024) NOT NULL,
    token_count         INT,
    metadata            JSONB,
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_program_chunk UNIQUE (support_program_id, chunk_index)
);
COMMENT ON TABLE  program_chunk IS '지원 사업 RAG 청크';
COMMENT ON COLUMN program_chunk.chunk_index IS '문서 내 순서';
COMMENT ON COLUMN program_chunk.embedding   IS 'nlpai-lab/KoE5 또는 KURE-v1 (1024차원). KoE5 사용 시 "passage: " 접두어, 512 토큰 이하';
COMMENT ON COLUMN program_chunk.metadata    IS '출처 섹션/페이지 등 필터용 메타데이터';
CREATE INDEX idx_program_chunk_embedding
    ON program_chunk USING hnsw (embedding vector_cosine_ops);

CREATE TABLE suggest_support_program (
    support_program_id  BIGINT    NOT NULL REFERENCES support_program(id) ON DELETE CASCADE,
    business_id         BIGINT    NOT NULL REFERENCES business_info(id)   ON DELETE CASCADE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason              VARCHAR(255),
    PRIMARY KEY (support_program_id, business_id)
);
COMMENT ON TABLE suggest_support_program IS '업체별 지원 사업 추천';

-- =====================================================================
-- 7. 즐겨찾기 / 신청
-- =====================================================================

CREATE TABLE bookmark (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT    NOT NULL REFERENCES users(id)           ON DELETE CASCADE,
    loan_id             BIGINT    REFERENCES loan(id)                     ON DELETE CASCADE,
    support_program_id  BIGINT    REFERENCES support_program(id)          ON DELETE CASCADE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_bookmark_target
        CHECK ((loan_id IS NULL) <> (support_program_id IS NULL))
);
COMMENT ON TABLE  bookmark IS '유저 즐겨찾기 (loan_id / support_program_id 중 정확히 하나)';
CREATE UNIQUE INDEX uq_bookmark_loan    ON bookmark(user_id, loan_id)            WHERE loan_id IS NOT NULL;
CREATE UNIQUE INDEX uq_bookmark_program ON bookmark(user_id, support_program_id) WHERE support_program_id IS NOT NULL;

CREATE TABLE application (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    business_id    BIGINT      REFERENCES business_info(id)  ON DELETE SET NULL,
    loan_id        BIGINT      REFERENCES loan(id)           ON DELETE SET NULL,
    status         VARCHAR(20) NOT NULL,
    reject_reason  VARCHAR(255),
    subject_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    complete_at    TIMESTAMP
);
COMMENT ON TABLE  application IS '대출 신청';
COMMENT ON COLUMN application.status IS '신청 준비중 / 신청 완료 / 심사 중 / 승인 / 반려';
CREATE INDEX idx_application_user ON application(user_id, status);

CREATE TABLE application_document (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id      BIGINT       NOT NULL REFERENCES application(id) ON DELETE CASCADE,
    document_type       VARCHAR(50)  NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    stored_path         VARCHAR(500) NOT NULL,
    validation_status   VARCHAR(50)  NOT NULL,
    validation_message  VARCHAR(255),
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE  application_document IS '신청 서류';
COMMENT ON COLUMN application_document.document_type      IS '검증 / 작성';
COMMENT ON COLUMN application_document.validation_status  IS '검증 준비중 / 검증 진행중 / 검증 통과 / 검증 실패 / 작성중 / 작성완료';
COMMENT ON COLUMN application_document.validation_message IS '검증 실패 시 사유';
CREATE INDEX idx_application_document_app ON application_document(application_id);
