CREATE TABLE automatic_transfer (
                                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    account_id  BIGINT      NOT NULL REFERENCES account(id) ON DELETE CASCADE,
                                    bank_name   VARCHAR(20) NOT NULL,
                                    account_no  VARCHAR(16) NOT NULL
);

COMMENT ON TABLE automatic_transfer IS '자동이체 계좌';
COMMENT ON COLUMN automatic_transfer.account_id IS '자동이체 출금 계좌 ID';
COMMENT ON COLUMN automatic_transfer.bank_name IS '자동이체 대상 은행명';
COMMENT ON COLUMN automatic_transfer.account_no IS '자동이체 대상 계좌번호';

CREATE INDEX idx_automatic_transfer_account
    ON automatic_transfer(account_id);