from enum import StrEnum


class RuntimeFieldStatus(StrEnum):
    RESOLVED = "RESOLVED"
    INPUT_REQUIRED = "INPUT_REQUIRED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNSUPPORTED = "UNSUPPORTED"
    VALUE_MISSING = "VALUE_MISSING"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    ERROR = "ERROR"
